version: '3'
services:
  db:
    image: mysql
    container_name: db
    volumes:
      - data:/var/lib/mysql
      - /Users/aleccunningham/Projects/student-advisor/sql/:docker-entrypoint-initdb.d/:ro
    ports:
      - 3306:3306
    expose:
      - "3306"
volumes:
    data:
