version: '3.3'

services:
  mysql:
    image: mysql
    container_name: "db"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=voyager
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./sql:/var/lib/mysql
    ports:
      - "3306:3306"
