version: '3'
     
services:
  app:
    build: .
    volumes:
      - ./student_advisor:/home/docker/student_advisor
    working_dir: /home/docker/student_advisor
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres 
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
    pg_data:
